const ADD_OBJECT = "ADD_OBJECT";
const CHANGE_OBJECT = "CHANGE_OBJECT";
const CHANGE_PATH = "CHANGE_PATH";
const CHANGE_VALUE = "CHANGE_VALUE";
const CLEAR_FORM = "CLEAR_FORM";

export { ADD_OBJECT, CHANGE_OBJECT, CHANGE_PATH, CHANGE_VALUE, CLEAR_FORM };
